apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xy6ntsahs-go 
  janus-idp.io/tekton: xy6ntsahs-go
  backstage.io/kubernetes-id: xy6ntsahs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xy6ntsahs-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  